package com.SIGMA.USCO.Modalities.Entity;

public enum ModalityProcessStatus {
    MODALITY_SELECTED,
    UNDER_REVIEW_SECRETARY,
    CORRECTIONS_REQUESTED_SECRETARY,
    READY_FOR_COUNCIL,
    UNDER_REVIEW_COUNCIL,
    CORRECTIONS_REQUESTED_COUNCIL,
    PROPOSAL_APPROVED,
    DEFENSE_SCHEDULED,
    DEFENSE_COMPLETED,
    GRADED_APPROVED,
    GRADED_FAILED,
    MODALITY_CANCELLED,
    MODALITY_CLOSED
}
