package com.SIGMA.USCO.Modalities.Entity.enums;


public enum AcademicDistinction {

    NO_DISTINCTION,
    AGREED_APPROVED,
    AGREED_MERITORIOUS,
    AGREED_LAUREATE,
    AGREED_REJECTED,
    DISAGREEMENT_PENDING_TIEBREAKER,
    TIEBREAKER_APPROVED,
    TIEBREAKER_MERITORIOUS,
    TIEBREAKER_LAUREATE,
    TIEBREAKER_REJECTED
}
