package com.SIGMA.USCO.Modalities.Entity.enums;

public enum     ModalityProcessStatus {
    MODALITY_SELECTED,
    UNDER_REVIEW_PROGRAM_HEAD,
    CORRECTIONS_REQUESTED_PROGRAM_HEAD,
    READY_FOR_PROGRAM_CURRICULUM_COMMITTEE,
    UNDER_REVIEW_PROGRAM_CURRICULUM_COMMITTEE,
    CORRECTIONS_REQUESTED_PROGRAM_CURRICULUM_COMMITTEE,
    PROPOSAL_APPROVED,
    DEFENSE_REQUESTED_BY_PROJECT_DIRECTOR,
    DEFENSE_SCHEDULED,
    DEFENSE_COMPLETED,
    GRADED_APPROVED,
    GRADED_FAILED,
    MODALITY_CANCELLED,
    MODALITY_CLOSED,
    CANCELLATION_REQUESTED,
    CANCELLATION_APPROVED_BY_PROJECT_DIRECTOR,
    CANCELLATION_REJECTED_BY_PROJECT_DIRECTOR,
    CANCELLED_WITHOUT_REPROVAL,
    CANCELLATION_REJECTED

}
