package com.SIGMA.USCO.notifications.entity.enums;

public enum NotificationType {

    MODALITY_STARTED,
    DOCUMENT_REVIEWED_BY_PROGRAM_HEAD,
    MODALITY_APPROVED_BY_PROGRAM_HEAD,
    MODALITY_APPROVED_BY_PROGRAM_CURRICULUM_COMMITTEE,
    MODALITY_REJECTED,
    MODALITY_CANCELLED,
    MODALITY_CANCELLATION_REQUESTED,
    MODALITY_CANCELLATION_APPROVED,
    MODALITY_CANCELLATION_REJECTED,
    MODALITY_CLOSED_BY_COMMITTEE,

    DOCUMENT_UPLOADED,
    DOCUMENT_APPROVED,
    DOCUMENT_REJECTED,
    DOCUMENT_CORRECTIONS_REQUESTED,
    CORRECTION_DEADLINE_REMINDER,
    CORRECTION_DEADLINE_EXPIRED,
    CORRECTION_RESUBMITTED,
    CORRECTION_APPROVED,
    CORRECTION_REJECTED_FINAL,

    DIRECTOR_ASSIGNED,
    DIRECTOR_CHANGED,

    DEFENSE_SCHEDULED,
    DEFENSE_COMPLETED,

    FINAL_APPROVED,
    FINAL_FAILED,


    MODALITY_INVITATION_RECEIVED,


    MODALITY_INVITATION_ACCEPTED,


    MODALITY_INVITATION_REJECTED,


    MODALITY_INVITATION_CANCELLED,


    MODALITY_MEMBER_JOINED,


    MODALITY_MEMBER_LEFT,


    MODALITY_GROUP_READY

}
