package com.SIGMA.USCO.notifications.entity.enums;

public enum NotificationType {

    MODALITY_STARTED,
    DOCUMENT_REVIEWED_BY_PROGRAM_HEAD,
    MODALITY_APPROVED_BY_PROGRAM_HEAD,
    MODALITY_APPROVED_BY_PROGRAM_CURRICULUM_COMMITTEE,
    MODALITY_REJECTED,
    MODALITY_CANCELLED,
    MODALITY_CANCELLATION_REQUESTED,
    MODALITY_CANCELLATION_APPROVED,
    MODALITY_CANCELLATION_REJECTED,

    DOCUMENT_UPLOADED,
    DOCUMENT_APPROVED,
    DOCUMENT_REJECTED,
    DOCUMENT_CORRECTIONS_REQUESTED,

    DIRECTOR_ASSIGNED,
    DIRECTOR_CHANGED,

    DEFENSE_SCHEDULED,
    DEFENSE_COMPLETED,

    FINAL_APPROVED,
    FINAL_FAILED

}
