package com.SIGMA.USCO.documents.entity;

public enum DocumentStatus {

    PENDING,
    ACCEPTED_FOR_SECRETARY_REVIEW,
    REJECTED_FOR_SECRETARY_REVIEW,
    CORRECTIONS_REQUESTED_BY_SECRETARY,
    ACCEPTED_FOR_COUNCIL_REVIEW,
    REJECTED_FOR_COUNCIL_REVIEW,
    CORRECTIONS_REQUESTED_BY_COUNCIL,
}
