package com.SIGMA.USCO.documents.entity;

public enum DocumentStatus {

    PENDING,
    ACCEPTED_FOR_PROGRAM_HEAD_REVIEW,
    REJECTED_FOR_PROGRAM_HEAD_REVIEW,
    CORRECTIONS_REQUESTED_BY_PROGRAM_HEAD,
    ACCEPTED_FOR_PROGRAM_CURRICULUM_COMMITTEE_REVIEW,
    REJECTED_FOR_PROGRAM_CURRICULUM_COMMITTEE_REVIEW,
    CORRECTIONS_REQUESTED_BY_PROGRAM_CURRICULUM_COMMITTEE

}
